name: 'Manage PR Assignees'
description: 'A github action that manages the assignee(s) of a PR in reaction to review requests & submissions'
branding:
    icon: 'check-circle'
    color: 'purple'
author: 'Evan Higgins'
inputs:
    token:
        description: A github access token that has adequate permissions to fetch a PR and change the assignee(s).
        required: true
runs:
    using: 'node16'
    main: 'dist/index.js'
