name: Manage assignees!
on:
    pull_request:
        types: [opened, reopened, review_requested, review_request_removed]
    pull_request_review:
        types: [submitted]

jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - uses: ./
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  pr-creator-assignee-substitutions: '{ "dependabot": "evdhiggins" }'
